infra: migrate to uv (#84)
* infra: migrate to uv

* infra: migrate to uv

* ci: remove extra from template

* ci: add changelog genny

* Update README.md

Co-authored-by: sourcery-ai[bot] <58596630+sourcery-ai[bot]@users.noreply.github.com>

* chore: update startcmd

* fix: adjust targets

* fix: adjust for dep updates

* fix: try to make railway happy

* fix: try to make railway happy again

* Revert "fix: try to make railway happy again"

This reverts commit b22d7576d9f67114476b016ac5138cb2e0c1c96f.

* fix: try to make railway happy again 3

* fix: try to make railway happy again 4

* fix: try to make railway happy again 5

* fix: try to make railway happy again 6

* fix: try to make railway happy again 7

* fix: try to make railway happy again 8

* fix: try to make railway happy again 9

* fix: try to make railway happy again 10

* fix: try to make railway happy again 11

* fix: try to make railway happy again 12

* fix: try to make railway happy again 13

* python packaging is so fucking stupid

* ci: apply lint

---------

Co-authored-by: sourcery-ai[bot] <58596630+sourcery-ai[bot]@users.noreply.github.com>

diff --git a/.github/workflows/docs-preview.yml b/.github/workflows/docs-preview.yml
--- a/.github/workflows/docs-preview.yml
+++ b/.github/workflows/docs-preview.yml
@@ -23,27 +23,33 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Download artifact
-        uses: dawidd6/action-download-artifact@v2
+        uses: dawidd6/action-download-artifact@v6
         with:
           workflow_conclusion: success
           run_id: ${{ github.event.workflow_run.id }}
           path: docs-preview
           name: docs-preview
 
-      - name: Set PR number
-        run: echo "PR_NUMBER=$(cat docs-preview/.pr_number)" >> $GITHUB_ENV
+      - name: Validate and set PR number
+        run: |
+          PR_NUMBER=$(cat docs-preview/.pr_number)
+          if ! [[ "$PR_NUMBER" =~ ^[0-9]+$ ]]; then
+            echo "Invalid PR number: $PR_NUMBER"
+            exit 1
+          fi
+          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
 
       - name: Deploy docs preview
         uses: JamesIves/github-pages-deploy-action@v4
         with:
           folder: docs-preview/docs/_build/html
-          token: ${{ secrets.DOCS_PREVIEW_DEPLOY_TOKEN }}
+          token: ${{ secrets.DOCS_PREVIEW_DEPLOY_KEY }}
           repository-name: JacobCoffee/byte-docs-preview
           clean: false
           target-folder: ${{ env.PR_NUMBER }}
           branch: gh-pages
 
-      - uses: actions/github-script@v6
+      - uses: actions/github-script@v7
         env:
           PR_NUMBER: ${{ env.PR_NUMBER }}
         with:
